routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');

Auth::routes();

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{slug}', 'PageController@slug')->name('blog.slug');
Route::post('/komentar', 'Artikel\ArtikelController@komentar')->name('blog.komentar');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:Admin,Writer']], function () {
    Route::get('/', 'PageController@dashboard')->name('dashboard');

    Route::group(['namespace' => 'Artikel'], function () {
        Route::get('/artikel/sampah', 'ArtikelController@sampah')->name('artikel.sampah');
        Route::post('/artikel/puilhkan/{id}', 'ArtikelController@restore')->name('artikel.restore');
        Route::Resource('/artikel', 'ArtikelController');

        Route::get('/kategori/sampah', 'KategoriController@sampah')->name('kategori.sampah');
        Route::post('/kategori/puilhkan/{id}', 'KategoriController@restore')->name('kategori.restore');
        Route::Resource('/kategori', 'KategoriController')->except(['show']);
    });

    Route::get('/webinar/sampah', 'WebinarController@sampah')->name('webinar.sampah');
    Route::post('/webinar/puilhkan/{id}', 'WebinarController@restore')->name('webinar.restore');
    Route::resource('/webinar', 'WebinarController');
});

app/Models/Kategori.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kategori extends Model
{
    use SoftDeletes, Uuids;

    protected $table = 'kategori';
    protected $casts = ['id' => 'string'];
    protected $guarded = [];

    public function artikel() {
        return $this->belongsToMany('App\Models\Artikel');
    }
}

app/Http/Controllers/Artikel/KategoriController.php
<?php

namespace App\Http\Controllers\Artikel;

use App\Models\Kategori;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Kategori\KategoriCreateRequest;
use App\Http\Requests\Kategori\KategoriUpdateRequest;

class KategoriController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
        $this->middleware('permission:create kategori', ['only' => ['store']]);
        $this->middleware('permission:read kategori',   ['only' => ['index']]);
        $this->middleware('permission:update kategori', ['only' => ['update', 'edit']]);
        $this->middleware('permission:delete kategori', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $kategori = Kategori::where('user_id', $user->id)->latest()->paginate(5);
        return view('dashboard.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KategoriCreateRequest $request)
    {
        try {
            $user = Auth::user();
            $user->kategori()->create($request->all());
            return redirect()->route('kategori.index')->with(['sukses' => 'Tambah Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::findOrFail($id);
        return view('dashboard.kategori.update', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KategoriUpdateRequest $request, $id)
    {
        try {
            $kategori = Kategori::findOrFail($id);
            $kategori->update($request->all());
            return redirect()->route('kategori.index')->with(['sukses' => 'Update Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kategori::find($id)->delete();
        return redirect()->route('kategori.index')->with(['sukses' => 'Hapus Kategori Berhasil']);
    }

    /**
     * Show all deleted data.
     *
     * @return \Illuminate\Http\Response
     */

    public function sampah() {
        $kategori = Kategori::onlyTrashed()->latest()->paginate(5);
        return view('dashboard.kategori.sampah', compact('kategori'));
    }

    /**
     * Restore data from delete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function restore($id) {
        try {
            $kategori = Kategori::onlyTrashed()->find($id);
            $kategori->restore();
            return redirect()->route('kategori.index')->with(['sukses' => 'Memulihkan Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }
}

resources/views/dashboard/kategori/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
      <div class="col-12">
         <div class="ibox">
            <div class="ibox-content">
               <form action="{{ route('kategori.store') }}" method="POST">
                  @csrf
                  @method("POST")
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label for="">Nama</label>
                           <input type="text" class="form-control @error('judul') is-invalid @enderror" name="judul" value="{{ old('judul') }}">
                           @error('judul')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Deskripsi</label>
                           <textarea name="deskripsi" id="" cols="5" rows="5" class="form-control @error('deskripsi') is-invalid @enderror">{{ old('deskripsi') }}</textarea>
                           @error('deskripsi')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror 
                        </div>
                     </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Tambah</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/dashboard/kategori/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content">
   <div class="animated fadeInRightBig">
      <div class="ibox ">
         <div class="ibox-title pb-3">
            <a href="{{ route('kategori.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Kategori</a>
            <a href="{{ route('kategori.sampah') }}" class="btn btn-outline-success">Sampah</a>
         </div>
         <div class="ibox-content">

            <table class="table table-bordered table-hover table-striped">
               <thead>
                  <tr>
                     <th>#</th>
                     <th>Nama Kategori</th>
                     <th>Deskripsi</th>
                     <th>Aksi</th>
                  </tr>
               </thead>
               <tbody>
                  @forelse ($kategori as $value)
                     <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $value->judul }}</td>
                        <td>{{ (strlen($value->deskripsi > 50) ? substr($value->deskripsi, 0, 50) : $value->deskripsi) }}</td>
                        <td>
                           <div class="btn-group d-flex" role="group">
                              <div class="btn-group mx-auto" role="group">
                              <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">Aksi</button>
                                 <div class="dropdown-menu"> 
                                    <a href="{{ route('kategori.edit', $value->id) }}" class="btn-detaildata dropdown-item text-success"><i class="fa fa-edit"></i> Edit</a>
                                    <form id="logout-form" action="{{ route('kategori.destroy', $value->id) }}" method="POST">
                                       @csrf
                                       @method("DELETE")
                                       <button class="btn-detaildata dropdown-item text-danger"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                 </div>
                              </div>
                           </div>
                        </td>
                     </tr>    
                  @empty
                      <tr>
                         <td colspan="4" class="text-center">Tidak ada data</td>
                      </tr>
                  @endforelse
               </tbody>
            </table>
            {{ $kategori->links() }}
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/dashboard/kategori/sampah.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content">
   <div class="animated fadeInRightBig">
      <div class="ibox ">
         <div class="ibox-content">
            <table class="table table-bordered table-hover">
               <thead>
                  <tr>
                     <th>#</th>
                     <th>Nama Kategori</th>
                     <th>Deskripsi</th>
                     <th>Aksi</th>
                  </tr>
               </thead>
               <tbody>
                  @forelse ($kategori as $value)
                     <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $value->judul }}</td>
                        <td>{{ (strlen($value->deskripsi > 50) ? substr($value->deskripsi, 0, 50) : $value->deskripsi) }}</td>
                        <td>
                           <form action="{{ route('kategori.restore', $value->id) }}" method="POST">
                              @csrf
                              <button type="submit" class="btn btn-warning">Pulihkan</button>
                           </form>
                        </td>
                     </tr>    
                  @empty
                      <tr>
                         <td colspan="4" class="text-center">Tidak ada data</td>
                      </tr>
                  @endforelse
               </tbody>
            </table>
            {{ $kategori->links() }}
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/dashboard/kategori/update.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
      <div class="col-12">
         <div class="ibox">
            <div class="ibox-content">
               <form action="{{ route('kategori.update', $kategori->id) }}" method="POST">
                  @csrf
                  @method("PUT")
                  <input type="hidden" name="id" value="{{ $kategori->id }}">
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label for="">Nama</label>
                           <input type="text" class="form-control @error('judul') is-invalid @enderror" name="judul" value="{{ $kategori->judul }}">
                           @error('judul')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Deskripsi</label>
                           <textarea name="deskripsi" id="" cols="5" rows="5" class="form-control @error('deskripsi') is-invalid @enderror">{{ $kategori->deskripsi }}</textarea>
                           @error('deskripsi')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror </div>
                     </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Update</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection