routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');

Auth::routes();

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{slug}', 'PageController@slug')->name('blog.slug');
Route::post('/komentar', 'Artikel\ArtikelController@komentar')->name('blog.komentar');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:Admin,Writer']], function () {
    Route::get('/', 'PageController@dashboard')->name('dashboard');

    Route::group(['namespace' => 'Artikel'], function () {
        Route::get('/artikel/sampah', 'ArtikelController@sampah')->name('artikel.sampah');
        Route::post('/artikel/puilhkan/{id}', 'ArtikelController@restore')->name('artikel.restore');
        Route::Resource('/artikel', 'ArtikelController');

        Route::get('/kategori/sampah', 'KategoriController@sampah')->name('kategori.sampah');
        Route::post('/kategori/puilhkan/{id}', 'KategoriController@restore')->name('kategori.restore');
        Route::Resource('/kategori', 'KategoriController')->except(['show']);
    });

    Route::get('/webinar/sampah', 'WebinarController@sampah')->name('webinar.sampah');
    Route::post('/webinar/puilhkan/{id}', 'WebinarController@restore')->name('webinar.restore');
    Route::resource('/webinar', 'WebinarController');
});

app/Models/Webinar.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Webinar extends Model
{
    use SoftDeletes, Uuids;

    protected $table = 'webinar';
    protected $casts = ['id' => 'string'];
    protected $guarded = [];
    protected $appends = ['gambar_url'];

    public function getGambarUrlAttribute() {
        if(isset($this->poster)) {
            return url('upload/webinar/' . $this->poster);
        } else {
            return url('images/user.png');
        }
    }
}

app/Http/Controllers/WebinarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Webinar;
use Illuminate\Http\Request;
use App\Traits\ImageHandlerTrait;
use App\Http\Requests\Webinar\WebinarCreateRequest;
use App\Http\Requests\Webinar\WebinarUpdateRequest;

class WebinarController extends Controller
{
    private $pathImage = "upload\webinar/";
    use ImageHandlerTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $webinar = Webinar::paginate(10);
        return view('dashboard.webinar.index', compact('webinar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.webinar.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WebinarCreateRequest $request)
    {
        try {
            $tglMulai = str_replace('/', '-', $request->mulai);
            $tglAkhir = str_replace('/', '-', $request->akhir);

            if(strtotime($tglMulai) > strtotime($tglAkhir)) {
                return redirect()->back()->with(['gagal' => 'Tanggal akhir tidak boleh mendahului Tanggal Mulai'])->withInput();
            }

            if ($request->file('image')) {
                $this->uploadImage($request, $this->pathImage);
            }
            $webinar = Webinar::create([
                'poster' => $request->gambar,
                'nama' => $request->nama,
                'url' => $request->url,
                'deskripsi' => $request->deskripsi,
                'mulai' => date('Y-m-d', strtotime($tglMulai)),
                'akhir' => date('Y-m-d', strtotime($tglAkhir))
            ]);
            return redirect()->route('webinar.index')->with(['sukses' => 'Tambah Webinar Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $webinar = Webinar::find($id);
            return view('dashboard.webinar.show', compact('webinar'));
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $webinar = Webinar::find($id);
        return view('dashboard.webinar.update', compact('webinar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(WebinarUpdateRequest $request, $id)
    {
        try {
            $tglMulai = str_replace('/', '-', $request->mulai);
            $tglAkhir = str_replace('/', '-', $request->akhir);

            if(strtotime($tglMulai) > strtotime($tglAkhir)) {
                return redirect()->back()->with(['gagal' => 'Tanggal akhir tidak boleh mendahului Tanggal Mulai'])->withInput();
            }

            if ($request->file('image')) {
                $this->uploadImage($request, $this->pathImage);
            }
            $webinar = Webinar::find($id);
            $webinar->update([
                'poster' => ($request->gambar != null) ? $request->gambar : $webinar->poster,
                'nama' => $request->nama,
                'url' => $request->url,
                'deskripsi' => $request->deskripsi,
                'mulai' => date('Y-m-d', strtotime($tglMulai)),
                'akhir' => date('Y-m-d', strtotime($tglAkhir))
            ]);
            return redirect()->route('webinar.index')->with(['sukses' => 'Update Webinar Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Webinar::find($id)->delete();
        return redirect()->route('webinar.index')->with(['sukses' => 'Hapus Webinar Berhasil']);
    }

    public function sampah() {
        $webinar = Webinar::onlyTrashed()->latest()->paginate(5);
        return view('dashboard.webinar.sampah', compact('webinar'));
    }

    /**
     * Restore data from delete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function restore($id) {
        try {
            $webinar = Webinar::onlyTrashed()->find($id);
            $webinar->restore();
            return redirect()->route('webinar.index')->with(['sukses' => 'Memulihkan Webinar Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }
}

resources/views/dashboard/webinar/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
      <div class="col-12">
         <div class="ibox">
            <div class="ibox-content">
               <form action="{{ route('webinar.store') }}" method="POST" enctype="multipart/form-data">
                  @csrf
                  @method("POST")
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label for="">Nama</label>
                           <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}">
                           @error('nama')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Url</label>
                           <input type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url') }}">
                           @error('url')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Deskripsi</label>
                           <textarea name="deskripsi" id="deskripsi" cols="5" rows="5" class="form-control @error('deskripsi') is-invalid @enderror">{{ old('deskripsi') }}</textarea>
                           @error('deskripsi')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror 
                        </div>
                        <div class="form-group">
                           <label for="">Gambar</label>
                           <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" accept="image/x-png,image/gif,image/jpeg">
                           <small>Max 5 mb</small>
                           @error('image')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group" id="mulai">
                                 <label class="font-normal">Tanggal Mulai</label>
                                 <div class="input-group date">
                                     <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control  @error('mulai') is-invalid @enderror" value="{{ date('d/m/Y') }}" name="mulai">
                                 </div>
                                 @error('mulai')
                                    <span class="invalid-feedback" role="alert">
                                       <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                             </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group" id="akhir">
                                 <label class="font-normal">Tanggal Berakhir</label>
                                 <div class="input-group date">
                                     <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control  @error('akhir') is-invalid @enderror" value="{{ date('d/m/Y') }}" name="akhir">
                                 </div>
                                 @error('akhir')
                                    <span class="invalid-feedback" role="alert">
                                       <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                             </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Tambah</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

@section('css')
   <link href="{{ asset('vendor/datepicker/datepicker3.css') }}" rel="stylesheet">
@endsection

@section('script')
   <script src="{{ asset('vendor/datepicker/bootstrap-datepicker.js') }}"></script>
   <script>
      $('#mulai .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         format: "dd/mm/yyyy"
      })

      $('#akhir .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         format: "dd/mm/yyyy",
         startDate: '+1d'
      })
   </script>
@endsection

resources/views/dashboard/webinar/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="wrapper wrapper-content">
        <div class="animated fadeInRightBig">
            <div class="ibox ">
                <div class="ibox-title pb-3">
                    <a href="{{ route('webinar.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah
                        Webinar</a>
                    <a href="{{ route('webinar.sampah') }}" class="btn btn-outline-success">Sampah</a>
                </div>
                <div class="ibox-content">

                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                <th>Poster</th>
                                <th>Deskripsi</th>
                                <th>Tanggal Mulai</th>
                                <th>Tanggal Selesai</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($webinar as $value)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $value->nama }}</td>
                                    <td><img src="{{ asset("upload/webinar/$value->poster") }}" alt="{{ $value->poster }}"
                                            class="img-fluid img-thumbnail mx-auto d-block" width="100"></td>
                                    <td>{{ strlen($value->deskripsi) > 50 ? substr($value->deskripsi, 0, 50) : $value->deskripsi }}
                                    </td>
                                    <td>{{ date('d, F Y', strtotime($value->mulai)) }}</td>
                                    <td>{{ date('d, F Y', strtotime($value->akhir)) }}</td>
                                    <td>
                                        <div class="btn-group d-flex" role="group">
                                            <div class="btn-group mx-auto" role="group">
                                                <button class="btn btn-success dropdown-toggle"
                                                    data-toggle="dropdown">Aksi</button>
                                                <div class="dropdown-menu">
                                                    <a href="{{ route('webinar.show', $value->id) }}"
                                                        class="btn-detaildata dropdown-item text-primary"><i
                                                            class="fa fa-eye"></i> Show</a>
                                                    <a href="{{ route('webinar.edit', $value->id) }}"
                                                        class="btn-detaildata dropdown-item text-success"><i
                                                            class="fa fa-edit"></i> Edit</a>
                                                    <form id="logout-form"
                                                        action="{{ route('webinar.destroy', $value->id) }}" method="POST">
                                                        @csrf
                                                        @method("DELETE")
                                                        <button class="btn-detaildata dropdown-item text-danger"><i
                                                                class="fa fa-trash"></i> Delete</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">Tidak ada data</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $webinar->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/webinar/sampah.blade.php
@extends('layouts.admin')

@section('content')
    <div class="wrapper wrapper-content">
        <div class="animated fadeInRightBig">
            <div class="ibox ">
                <div class="ibox-title pb-3">
                    <a href="{{ route('webinar.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah
                        Webinar</a>
                    <a href="{{ route('webinar.index') }}" class="btn btn-success">Kembali</a>
                </div>
                <div class="ibox-content">

                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                <th>Poster</th>
                                <th>Deskripsi</th>
                                <th>Tanggal Mulai</th>
                                <th>Tanggal Selesai</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($webinar as $value)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $value->nama }}</td>
                                    <td><img src="{{ asset("upload/webinar/$value->poster") }}" alt="{{ $value->poster }}"
                                            class="img-fluid img-thumbnail mx-auto d-block" width="100"></td>
                                    <td>{{ strlen($value->deskripsi) > 50 ? substr($value->deskripsi, 0, 50) : $value->deskripsi }}
                                    </td>
                                    <td>{{ date('d, F Y', strtotime($value->mulai)) }}</td>
                                    <td>{{ date('d, F Y', strtotime($value->akhir)) }}</td>
                                    <td>
                                        <form action="{{ route('webinar.restore', $value->id) }}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn btn-warning">Pulihkan</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">Tidak ada data</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $webinar->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/webinar/update.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
      <div class="col-12">
         <div class="ibox">
            <div class="ibox-content">
               <form action="{{ route('webinar.update', $webinar->id) }}" method="POST" enctype="multipart/form-data">
                  @csrf
                  @method("PUT")
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label for="">Nama</label>
                           <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ $webinar->nama }}">
                           @error('nama')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Url</label>
                           <input type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ $webinar->url }}">
                           @error('url')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Deskripsi</label>
                           <textarea name="deskripsi" id="deskripsi" cols="5" rows="5" class="form-control @error('deskripsi') is-invalid @enderror">{{ $webinar->deskripsi }}</textarea>
                           @error('deskripsi')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror 
                        </div>
                        <div class="form-group">
                           <div class="row">
                              <div class="col-md-6">
                                 <label for="">Gambar</label>
                                 <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" accept="image/x-png,image/gif,image/jpeg">
                                 <p>Kosongkan jika tidak update gambar</p>
                                 <small>Max 5 mb</small>
                              </div>
                              <div class="col-md-6 text-center">
                                 <img src="{{ $webinar->gambar_url }}" alt="{{ $webinar->gambar }}" width="200">
                              </div>
                           </div>
                           @error('image')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="row">
                           <div class="col-md-6">
                              <div class="form-group" id="mulai">
                                 <label class="font-normal">Tanggal Mulai</label>
                                 <div class="input-group date">
                                     <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control  @error('mulai') is-invalid @enderror" value="{{ date('d/m/Y', strtotime($webinar->mulai)) }}" name="mulai">
                                 </div>
                                 @error('mulai')
                                    <span class="invalid-feedback" role="alert">
                                       <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                             </div>
                           </div>
                           <div class="col-md-6">
                              <div class="form-group" id="akhir">
                                 <label class="font-normal">Tanggal Berakhir</label>
                                 <div class="input-group date">
                                     <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control  @error('akhir') is-invalid @enderror" value="{{ date('d/m/Y', strtotime($webinar->akhir)) }}" name="akhir">
                                 </div>
                                 @error('akhir')
                                    <span class="invalid-feedback" role="alert">
                                       <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                             </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Tambah</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

@section('css')
   <link href="{{ asset('vendor/datepicker/datepicker3.css') }}" rel="stylesheet">
@endsection

@section('script')
   <script src="{{ asset('vendor/datepicker/bootstrap-datepicker.js') }}"></script>
   <script>
      $('#mulai .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         format: "dd/mm/yyyy"
      })

      $('#akhir .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         format: "dd/mm/yyyy",
         startDate: '+1d'
      })
   </script>
@endsection