routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');

Auth::routes();

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{slug}', 'PageController@slug')->name('blog.slug');
Route::post('/komentar', 'Artikel\ArtikelController@komentar')->name('blog.komentar');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:Admin,Writer']], function () {
    Route::get('/', 'PageController@dashboard')->name('dashboard');

    Route::group(['namespace' => 'Artikel'], function () {
        Route::get('/artikel/sampah', 'ArtikelController@sampah')->name('artikel.sampah');
        Route::post('/artikel/puilhkan/{id}', 'ArtikelController@restore')->name('artikel.restore');
        Route::Resource('/artikel', 'ArtikelController');

        Route::get('/kategori/sampah', 'KategoriController@sampah')->name('kategori.sampah');
        Route::post('/kategori/puilhkan/{id}', 'KategoriController@restore')->name('kategori.restore');
        Route::Resource('/kategori', 'KategoriController')->except(['show']);
    });

    Route::get('/webinar/sampah', 'WebinarController@sampah')->name('webinar.sampah');
    Route::post('/webinar/puilhkan/{id}', 'WebinarController@restore')->name('webinar.restore');
    Route::resource('/webinar', 'WebinarController');
});

resources/views/layouts/partials/breadcrumb.blade.php
<div class="row wrapper border-bottom white-bg page-heading">
   <div class="col-sm-4">
      <h2>{{ $title ?? 'Admin Dashboard' }}</h2>
      <ol class="breadcrumb">
         <li class="breadcrumb-item {{ (Request::segment(1) == 'dashboard') ? 'active' : '' }}">
            <a href="{{ url('/') }}">Home</a>
         </li>
         @if (Request::segment(2) != 'dashboard')
            <li class="breadcrumb-item active">
               <strong>{{ Request::segment(2) }}</strong>
            </li>
         @endif
      </ol>
   </div>
   {{-- <div class="col-sm-8">
      <div class="title-action">
         <a href="" class="btn btn-primary">This is action area</a>
      </div>
   </div> --}}
</div>

resources/views/layouts/partials/footer.blade.php
<div class="footer">
    <div class="float-right">
        Ini Footer Cuy
    </div>
    <div>
        <strong>Copyright</strong>&copy; 2021 @if (date('Y') != '2021') -
            {{ date('Y') }}@endif
    </div>
</div>

resources/views/layouts/partials/navbar.blade.php
<div class="row border-bottom">
   <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
         <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i>
         </a>
         <form role="search" class="navbar-form-custom" action="search_results.html">
            <div class="form-group">
               <input type="text" placeholder="Search for something..." class="form-control" name="top-search"
                  id="top-search">
            </div>
         </form>
      </div>
      <ul class="nav navbar-top-links navbar-right">
         <li>
            <a onclick="event.preventDefault();document.getElementById('logout-form').submit();">
               <i class="fa fa-sign-out"></i> Log out
            </a>
         </li>
      </ul>

   </nav>
</div>

resources/views/layouts/partials/sidebar.blade.php
@php
$segment = Request::segment(1);
$segment2 = Request::segment(2);
$segment3 = Request::segment(3);
@endphp
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <img alt="image" class="rounded-circle img-fluid" width="50"
                        src="{{ asset('images/user.png') }}" />
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">{{ Auth::user()->name }}</span>
                        <span class="text-muted text-xs block">{{ Auth::user()->getRoleNames()->first() }} <b
                                class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item"
                                onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="{{ $segment2 == '' ? 'active' : '' }}">
                <a href="{{ route('dashboard') }}"><i class="fa fa-th-large"></i> <span
                        class="nav-label">Home</span></a>
            </li>
            <li class="{{ $segment2 == 'artikel' || $segment2 == 'kategori' ? 'active' : '' }}">
                <a href="javascript:void(0)"><i class="fa fa-newspaper-o"></i> <span class="nav-label">Artikel</span>
                    <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="{{ $segment2 == 'artikel' ? 'active' : '' }}"><a
                            href="{{ route('artikel.index') }}">Artikel</a></li>
                    <li class="{{ $segment2 == 'kategori' ? 'active' : '' }}"><a
                            href="{{ route('kategori.index') }}">Kategori</a></li>
                </ul>
            </li>
            <li class="{{ $segment2 == 'webinar' ? 'active' : '' }}">
                <a href="{{ route('webinar.index') }}"><i class="fa fa-th-large"></i> <span
                        class="nav-label">Webinar</span></a>
            </li>
        </ul>

    </div>
</nav>