routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');

Auth::routes();

Route::get('/blog', 'PageController@blog')->name('blog.index');
Route::get('/blog/{slug}', 'PageController@slug')->name('blog.slug');
Route::post('/komentar', 'Artikel\ArtikelController@komentar')->name('blog.komentar');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:Admin,Writer']], function () {
    Route::get('/', 'PageController@dashboard')->name('dashboard');

    Route::group(['namespace' => 'Artikel'], function () {
        Route::get('/artikel/sampah', 'ArtikelController@sampah')->name('artikel.sampah');
        Route::post('/artikel/puilhkan/{id}', 'ArtikelController@restore')->name('artikel.restore');
        Route::Resource('/artikel', 'ArtikelController');

        Route::get('/kategori/sampah', 'KategoriController@sampah')->name('kategori.sampah');
        Route::post('/kategori/puilhkan/{id}', 'KategoriController@restore')->name('kategori.restore');
        Route::Resource('/kategori', 'KategoriController')->except(['show']);
    });

    Route::get('/webinar/sampah', 'WebinarController@sampah')->name('webinar.sampah');
    Route::post('/webinar/puilhkan/{id}', 'WebinarController@restore')->name('webinar.restore');
    Route::resource('/webinar', 'WebinarController');
});

app/Models/Artikel.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Artikel extends Model
{
    use SoftDeletes, Uuids;

    protected $table = 'artikel';
    protected $casts = ['id' => 'string'];
    protected $guarded = [];
    protected $with = ['kategori'];
    protected $appends = ['gambar_url'];

    public function kategori() {
        return $this->belongsToMany('App\Models\Kategori', 'artikel_kategori', 'artikel_id', 'kategori_id');
    }

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function komentar() {
        return $this->hasMany('App\Models\Komentar');
    }

    public function getGambarUrlAttribute() {
        if(isset($this->gambar)) {
            return url('upload/artikel/' . $this->gambar);
        } else {
            return url('images/user.png');
        }
    }
}

app/Http/Controllers/Artikel/ArtikelController.php
<?php

namespace App\Http\Controllers\Artikel;

use App\Models\Artikel;
use App\Models\Kategori;
use App\Models\Komentar;
use Illuminate\Http\Request;
use App\Traits\ImageHandlerTrait;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\KomentarCreateRequest;
use App\Http\Requests\Artikel\ArtikelCreateRequest;
use App\Http\Requests\Artikel\ArtikelUpdateRequest;

class ArtikelController extends Controller
{
    private $pathImage = "upload\artikel/";
    use ImageHandlerTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth')->except(['komentar']);
        $this->middleware('permission:create artikel', ['only' => ['store']]);
        $this->middleware('permission:read artikel',   ['only' => ['index', 'show']]);
        $this->middleware('permission:update artikel', ['only' => ['update', 'edit']]);
        $this->middleware('permission:delete artikel', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $artikel = Artikel::where('user_id', $user->id)->paginate(10);
        return view('dashboard.artikel.index', compact('artikel'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        return view('dashboard.artikel.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArtikelCreateRequest $request)
    {
        try {
            if ($request->file('image')) {
                $this->uploadImage($request, $this->pathImage);
            }
            $user = Auth::user();
            $artikel = Artikel::create([
                'gambar' => $request->gambar,
                'nama' => $request->nama,
                'deskripsi' => $request->deskripsi,
                'slug' => \Str::slug($request->nama),
                'user_id' => $user->id,
                'status' => $request->status
            ]);
            $artikel->kategori()->attach($request->kategori);
            return redirect()->route('artikel.index')->with(['sukses' => 'Tambah Artikel Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $artikel = Artikel::find($id);
            return view('dashboard.artikel.show', compact('artikel'));
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $artikel = Artikel::find($id);
        $kategori = Kategori::all();
        return view('dashboard.artikel.update', compact('artikel', 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArtikelUpdateRequest $request, $id)
    {
        try {
            if ($request->file('image')) {
                $this->uploadImage($request, $this->pathImage);
            }
            $user = Auth::user();
            $artikel = Artikel::find($id);
            $artikel->update([
                'gambar' => ($request->gambar != null) ? $request->gambar : $artikel->gambar,
                'nama' => $request->nama,
                'deskripsi' => $request->deskripsi,
                'slug' => \Str::slug($request->nama),
                'status' => $request->status
            ]);
            $artikel->kategori()->attach($request->kategori);
            return redirect()->route('artikel.index')->with(['sukses' => 'Update Artikel Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Artikel::find($id)->delete();
        return redirect()->route('artikel.index')->with(['sukses' => 'Hapus Artikel Berhasil']);
    }

    public function sampah() {
        $artikel = Artikel::onlyTrashed()->latest()->paginate(5);
        return view('dashboard.artikel.sampah', compact('artikel'));
    }

    /**
     * Restore data from delete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function restore($id) {
        try {
            $artikel = Artikel::onlyTrashed()->find($id);
            $artikel->restore();
            return redirect()->route('artikel.index')->with(['sukses' => 'Memulihkan Artikel Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Comment Article.
     *
     * @return \Illuminate\Http\Response
     */

    public function komentar(KomentarCreateRequest $request) {
        try {
            Komentar::create($request->all());
            return redirect()->back();
        } catch(\Exception $e) {
            echo $e->getMessage();
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }
}

app/Http/Controllers/Artikel/KategoriController.php
<?php

namespace App\Http\Controllers\Artikel;

use App\Models\Kategori;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Kategori\KategoriCreateRequest;
use App\Http\Requests\Kategori\KategoriUpdateRequest;

class KategoriController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
        $this->middleware('permission:create kategori', ['only' => ['store']]);
        $this->middleware('permission:read kategori',   ['only' => ['index']]);
        $this->middleware('permission:update kategori', ['only' => ['update', 'edit']]);
        $this->middleware('permission:delete kategori', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $kategori = Kategori::where('user_id', $user->id)->latest()->paginate(5);
        return view('dashboard.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KategoriCreateRequest $request)
    {
        try {
            $user = Auth::user();
            $user->kategori()->create($request->all());
            return redirect()->route('kategori.index')->with(['sukses' => 'Tambah Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::findOrFail($id);
        return view('dashboard.kategori.update', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KategoriUpdateRequest $request, $id)
    {
        try {
            $kategori = Kategori::findOrFail($id);
            $kategori->update($request->all());
            return redirect()->route('kategori.index')->with(['sukses' => 'Update Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kategori::find($id)->delete();
        return redirect()->route('kategori.index')->with(['sukses' => 'Hapus Kategori Berhasil']);
    }

    /**
     * Show all deleted data.
     *
     * @return \Illuminate\Http\Response
     */

    public function sampah() {
        $kategori = Kategori::onlyTrashed()->latest()->paginate(5);
        return view('dashboard.kategori.sampah', compact('kategori'));
    }

    /**
     * Restore data from delete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function restore($id) {
        try {
            $kategori = Kategori::onlyTrashed()->find($id);
            $kategori->restore();
            return redirect()->route('kategori.index')->with(['sukses' => 'Memulihkan Kategori Berhasil']);
        } catch(\Exception $e) {
            return redirect()->back()->with(['gagal' => $e->getMessage()])->withInput();
        }
    }
}

resources/views/dashboard/artikel/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
      <div class="col-12">
         <div class="ibox">
            <div class="ibox-content">
               <form action="{{ route('artikel.store') }}" method="POST" enctype="multipart/form-data">
                  @csrf
                  @method("POST")
                  <div class="row">
                     <div class="col-md-12">
                        <div class="form-group">
                           <label for="">Judul</label>
                           <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}">
                           @error('nama')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Isi Artikel</label>
                           <textarea name="deskripsi" id="deskripsi" cols="5" rows="5" class="form-control @error('deskripsi') is-invalid @enderror">{{ old('deskripsi') }}</textarea>
                           @error('deskripsi')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror 
                        </div>
                        <div class="form-group">
                           <label for="">Kategori</label>
                           <select name="kategori[]" id="selectKategori" class="form-control" multiple="multiple">
                              <option value="">-- Pilih --</option>
                              @foreach ($kategori as $value)
                                  <option value="{{ $value->id }}">{{ $value->judul }}</option>
                              @endforeach
                           </select>
                        </div>
                        <div class="form-group">
                           <label for="">Gambar</label>
                           <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" accept="image/x-png,image/gif,image/jpeg">
                           <small>Max 5 mb</small>
                           @error('image')
                           <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                           </span>
                           @enderror
                        </div>
                        <div class="form-group">
                           <label for="">Status</label>
                           <select name="status" class="form-control" required>
                              <option value="" selected disabled>-- Pilih --</option>
                              <option value="1">Draft</option>
                              <option value="2">Published</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Tambah</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

@section('script')
<script src="{{ asset('vendor/select2/select2.full.min.js') }}"></script>
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script>
   const options = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
   }

   CKEDITOR.replace('deskripsi', options)

   $(() => {
      $('#selectKategori').select2()
   })
</script>
@endsection

@section('css')
   <link rel="stylesheet" href="{{ asset('vendor/select2/select2.min.css') }}">
@endsection

resources/views/dashboard/artikel/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="wrapper wrapper-content">
        <div class="animated fadeInRightBig">
            <div class="ibox ">
                <div class="ibox-title pb-3">
                    <a href="{{ route('artikel.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah
                        Artikel</a>
                    <a href="{{ route('artikel.sampah') }}" class="btn btn-outline-success">Sampah</a>
                </div>
                <div class="ibox-content">

                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Gambar</th>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($artikel as $value)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td><img src="{{ asset("upload/artikel/$value->gambar") }}" alt="{{ $value->gambar }}"
                                            class="img-fluid img-thumbnail mx-auto d-block" width="100"></td>
                                    <td>{{ $value->nama }}</td>
                                    @php
                                        $isi = preg_replace('/&#?[a-z0-9]+;/i', ' ', $value->deskripsi);
                                    @endphp
                                    <td>{{ strlen(strip_tags($isi)) > 50 ? substr(strip_tags($isi), 0, 50) : strip_tags($isi) }}
                                    </td>
                                    <td>
                                        <div class="btn-group d-flex" role="group">
                                            <div class="btn-group mx-auto" role="group">
                                                <button class="btn btn-success dropdown-toggle"
                                                    data-toggle="dropdown">Aksi</button>
                                                <div class="dropdown-menu">
                                                    <a href="{{ route('artikel.show', $value->id) }}"
                                                        class="btn-detaildata dropdown-item text-primary"><i
                                                            class="fa fa-eye"></i> Show</a>
                                                    <a href="{{ route('artikel.edit', $value->id) }}"
                                                        class="btn-detaildata dropdown-item text-success"><i
                                                            class="fa fa-edit"></i> Edit</a>
                                                    <form id="logout-form" action="{{ route('artikel.destroy', $value->id) }}"
                                                        method="POST">
                                                        @csrf
                                                        @method("DELETE")
                                                        <button class="btn-detaildata dropdown-item text-danger"><i
                                                                class="fa fa-trash"></i> Delete</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center">Tidak ada data</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $artikel->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/artikel/sampah.blade.php
@extends('layouts.admin')

@section('content')
    <div class="wrapper wrapper-content">
        <div class="animated fadeInRightBig">
            <div class="ibox ">
                <div class="ibox-title pb-3">
                    <a href="{{ route('artikel.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah
                        Artikel</a>
                    <a href="{{ route('artikel.index') }}" class="btn btn-success">Kembali</a>
                </div>
                <div class="ibox-content">

                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Gambar</th>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($artikel as $value)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td><img src="{{ asset("upload/artikel/$value->gambar") }}" alt="{{ $value->gambar }}"
                                            class="img-fluid img-thumbnail mx-auto d-block" width="100"></td>
                                    <td>{{ $value->nama }}</td>
                                    @php
                                        $isi = preg_replace('/&#?[a-z0-9]+;/i', ' ', $value->deskripsi);
                                    @endphp
                                    <td>{{ strlen(strip_tags($isi)) > 50 ? substr(strip_tags($isi), 0, 50) : strip_tags($isi) }}
                                    </td>
                                    <td>
                                        <form action="{{ route('artikel.restore', $value->id) }}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn btn-warning">Pulihkan</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center">Tidak ada data</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {{ $artikel->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/artikel/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content  animated fadeInRight article">
   <div class="row justify-content-md-center">
      <div class="col-lg-10">
         <div class="ibox">
            <div class="ibox-content">
               <div class="float-right">
                  <button class="btn {{ ($artikel->status == 2) ? 'btn-white' : 'btn-primary' }} btn-xs" type="button">Draft</button>
                  <button class="btn {{ ($artikel->status == 1) ? 'btn-white' : 'btn-primary' }} btn-xs" type="button">Published</button>
                  {{-- <button class="btn btn-white btn-xs" type="button">Sampah</button> --}}
              </div>
              <div class="text-center article-title">
               <span class="text-muted"><i class="fa fa-clock-o"></i> {{ date('d F Y', strtotime( $artikel->created_at)) }}</span>
                   <h1>
                       {{ $artikel->nama }}
                   </h1>
                   <img alt="Re zero" src="{{ $artikel->gambar_url }}" width="300">
               </div>
               <div>
                  @php
                     $string = preg_replace("/&#?[a-z0-9]+;/i", " ", $artikel->deskripsi);
                  @endphp
                  {!! $string !!}
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-6">
                     <h5>Tags :</h5>
                     @foreach ($artikel->kategori as $value)
                        <button class="btn btn-primary btn-xs" type="button">{{ $value->judul }}</button>
                     @endforeach
                  </div>
                  <div class="col-md-6">
                     <div class="small text-right">
                        <h5>Stats:</h5>
                        <div> <i class="fa fa-comments-o"> </i> 56 comments </div>
                    </div>
                  </div>
               </div>

               <div class="row">
                  <div class="col-lg-12">
                     <h2>Comments:</h2>
                     <div class="social-feed-box">
                        <div class="social-avatar">
                            <a href="" class="float-left">
                                <img alt="image" src="img/a1.jpg">
                            </a>
                        </div>
                        <div class="social-body">
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque ipsa tempora praesentium vitae soluta optio quaerat! Est vel iure eveniet?
                            </p>
                        </div>
                    </div>
                  </div>
               </div>

            </div>
         </div>
      </div>
   </div>
</div>
@endsection